data:
  train_bs: 8
  train_width: 768 
  train_height: 768
  drop_ratio: 0.1
  style_ratio: 0.01

solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: True
  gradient_checkpointing: False 
  max_train_steps: 120000
  max_grad_norm: 1.0
  # lr
  learning_rate: 1.0e-5
  scale_lr: False 
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: False 
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 3000


noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "scaled_linear"
  steps_offset:        1
  clip_sample:         false

base_model_path: './pretrained_weights/sd-image-variations-diffusers'
vae_model_path: './pretrained_weights/sd-vae-ft-mse'
image_encoder_path: './pretrained_weights/sd-image-variations-diffusers/image_encoder'
pretrained_denoising_unet: './pretrained_weights/denoising_unet-60000.pth'
pretrained_reference_unet: './pretrained_weights/reference_unet-60000.pth'

weight_dtype: 'fp16'
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True 

seed: 186
resume_from_checkpoint: ''
checkpointing_steps: 3000
save_model_epoch_interval: 1
save_model_step_interval: 3000
exp_name: 'train_stage1_mikudance'
output_dir: './train_output'